export { default as Profile } from "./Profile"
export { default as Skills } from "./Skills"
export { default as Academic } from "./Academic"
export { default as Experience } from "./Experience"
export { default as Projects } from "./Projects"
export { default as Blog } from "./Blog"